### ISSUE TITLE
"Link Preview" feature will chain crash a discord channel if something is linked which is blocked in the hosts file

### ISSUE THREAD

**Issue by quimbydogg** [discordlinux/support#10]
## Discord Username
quimby#0414

## Expected Behavior

If "Link Preview" feature is enabled and a URL linked by someone has an error, the client should "handle that": either by displaying a preview of the error or simply not displaying a preview for that specific URL.  The key behavior would be that the channel does not crash when the URL is received with the "Link Preview" feature enabled.

## Actual Behavior

When a URL is blocked via hosts file and someone in a Discord channel links to the blocked domain the Discord channel will crash trying to preview the link.  When the channel reloads it will instantly crash again trying to preview the link.  I was only able to stop the channel crashing by disabling the "Link Preview" option.

## Steps to Reproduce the Problem

  1. Block URL (such as open.spotify.com) within hosts file by re-directing home (127.0.0.1).
  2. Receive Discord message from someone in channel which is at that URL with "Link Preview" enabled

## Specifications

  - Platform: Gentoo 4.16.5

**Comment by simoniz0r** [comment]
This is a known issue.  This is also not the place to report Discord bugs.

Issue:
https://trello.com/c/O9XFKh4e

Report Discord bugs here:
http://discord.gg/discord-testers

**Comment by quimbydogg** [comment]
Ahh thanks, glad to know this is already tracked somewhere.  Was shocked to see that another user could send a link that would make the channel inoperable.  Was re-directed here from my initial e-mail to support, sorry for any confusion!
