### ISSUE TITLE
Kali linux wont booy, probably due to no storage left.

### ISSUE THREAD

**Issue by Mobles** [discordlinux/support#13]
## Discord Username
Mobie

## Expected Behavior
Boot up as usual

## Actual Behavior
I get a blinking screen when kali is first loading

## Steps to Reproduce the Problem

  1. Probably due to full storage
  2.
  3.

## Specifications

  - Version: Latest
  - Platform: Kali Linux
  - Subsystem:
  
## Screenshots
https://cdn.discordapp.com/attachments/247786587398733824/440965922279260180/JPEG_20180501_210020.jpg

**Comment by simoniz0r** [comment]
Sorry, we do not support Kali.

**Comment by Mobles** [comment]
Welp, is it a global thing anyway?
