### ISSUE TITLE
Funky touchscreen behaviour

### ISSUE THREAD

**Issue by Altreus** [discordlinux/support#15]
## Discord Username

altreus

## Expected Behaviour

All gadgets and widgets open in the app when poked with meat

## Actual Behaviour

Private messages open in default browser when poked with meat.

Occasionally, servers also open in browser. But this is hard to reproduce.

I have also observed that at some point it gets the hang of it and behaves correctly. I have not investigated in depth.

## Steps to Reproduce the Problem

  1. Have touchscreen
  2. Install Linux client
  3. Convince someone to DM you
  4. Either:
  4a. Receive DM from person
  4b. Navigate to DMs area
  5. Poke person from 3. with meat
  6. Close browser window and retry with mouse

## Specifications

  - Version: 0.0.5
  - Platform: Debian
  - Subsystem: stretch

**Comment by Altreus** [comment]
It's an Electron app, right? I wonder whether it's related to Chrome's occasional hare-brained decision to download a link instead of following it...

**Comment by simoniz0r** [comment]
Please report Discord issues to Discord Testers, thanks.
https://discord.gg/discord-testers
