### ISSUE TITLE
snap package received audio cuts in and out

### ISSUE THREAD

**Issue by 2E0PGS** [discordlinux/support#18]
## Expected Behavior

Clear audio on receive.

## Actual Behavior

Audio cuts in and out, infact there is more silence than audio.

## Steps to Reproduce the Problem

  1. `sudo apt-get install snapd`
  2. `sudo snap install discord`
  3. Wait it to update then connect to voice with another user and try receiving.

## Specifications

  - Version: 1 Apr 2018 because there isn't a clear in app version number. Especially when launcher can be different version from actual electron app.
  - Platform: Ubuntu 16.04 x64
  - Subsystem: What subsystem? 
  
## Screenshots
![image](https://user-images.githubusercontent.com/15659301/39640747-df95d76a-4fc3-11e8-928d-0222ccb2498c.png)

## Debug log

I would attach the voice debugging log I enabled in the settings but it isn't specified where I can find that too.

**Comment by simoniz0r** [comment]
I suggest you try the [deb package provided by Discord](https://discordapp.com/api/download?platform=linux&format=deb).

If you continue to have issues with the deb package, please report an issue at [Discord Testers](https://discord.gg/discord-testers).

If you'd like to continue using the snap, please report your issue [here](https://github.com/snapcrafters/discord/issues).

**Comment by 2E0PGS** [comment]
FYI exact same thing happens with deb package.

**Comment by simoniz0r** [comment]
Please report an issue at [Discord Testers](https://discord.gg/discord-testers).

**Comment by 2E0PGS** [comment]
OK would you like to reopen the issue here however?

**Comment by simoniz0r** [comment]
If you find it's not an issue with the client and actually an issue on your end, sure.

**Comment by 2E0PGS** [comment]
So this repo is for general Linux support and not do to with the discord Linux client?

**Comment by simoniz0r** [comment]
Yes, that would be correct :D

**Comment by 2E0PGS** [comment]
Oh I see this is related to the community on Discord called Discord Linux. My mistake I thought this was an official Discord repo. I was once part of the Discord Linux discord server once. Cheers for now!
