### ISSUE TITLE
general doubt

### ISSUE THREAD

**Issue by sergio200hs** [discordlinux/support#21]
Hello, I'm seeing that the sound sharing in Linux has not yet appeared (nor in the canary)
Can you tell me when you're leaving?

only another question aside because the Linux discord has to be always downloading install when it updates (so it's a bit annoying since windows is one time and I was already (when I was still using))??

**Comment by simoniz0r** [comment]
Please report any Discord issues to Discord Testers https://discord.gg/discord-testers
