### ISSUE TITLE
Don't ship postinst.sh

### ISSUE THREAD

**Issue by Thaodan** [discordlinux/support#22]
postinst.sh currently does some malicious behaviour that should be avoided at all costs.
Don't modify the session of every user running!
If all these steps are needed do them during start of the program but not here.
Updating discord shouldn't kill discord and modify $HOME.

## Discord Username
Thaodan#7558 (does that really matter?)

## Expected Behavior
Don't do stuff like this.

## Actual Behavior
Do stuff like this.

## Steps to Reproduce the Problem

  1. try to package discord
  2. look in the tar-ball
  3. See post-inst.sh

## Specifications

  - Version: 0.5
  - Platform: linux, arch-linux
  - Subsystem:

**Comment by simoniz0r** [comment]
https://discord.gg/discord-testers
